const mongoose = require("mongoose");

const dataSchema = mongoose.Schema({
    name: String,
    userID: String,
    lb: String,
    money: Number,
    heartMoney: Number,
    daily: Number,
    hourlyTip: Number,
    numDay: Number,
    numTotalDays: Number,
    bakeryName: String,
    ovenTime: Number,
    barTime: Number,
    ovenInfo: String,
    barInfo: String,
    ovenHearts: String,
    barHearts: String,
    shopItem: String,
    ovenItem: String,
    barItem: String,
    customer1Time: Number,
    customer2Time: Number,
    customer3Time: Number,
    customer4Time: Number,
    customer1Count: Number,
    customer2Count: Number,
    customer3Count: Number,
    customer4Count: Number,
    grannyCount: Number,
    currentOrder: String,
    currentOrderPastry: String,
    currentOrderDrink: String,
    adviceC1: String,
    adviceC2: String,
    adviceC3: String,
    adviceC4: String,
    chooseAdvice: String,
    timesCompleted: Number,
})

module.exports = mongoose.model("Data", dataSchema);